# Generated by Django 3.0.8 on 2020-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
            ],
        ),
    ]
