# Generated by Django 3.0.8 on 2020-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
